[workspace]
resolver = "2"

members = ["libprotonup", "protonup-rs"]

[profile.release]
opt-level = 3
debug = false
lto = true
strip = "debuginfo"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
