[package]
name = "libprotonup"
version = "0.7.0"
edition = "2021"
authors = ["Auyer <auyer@rcpassos.me>"]
repository = "https://github.com/auyer/protonup-rs"
license = "Apache-2.0"
readme = "../README.md"

description = "Library for Custom Proton Download and installation"

[dependencies]
arcstr = "1.1.5"
anyhow = "1.0"
async-compression = { version = "0.4.6", features = ['gzip', 'xz', 'tokio'] }
dirs = "5.0"
futures-util = "0.3"
hex = "0.4"
hex-literal = "0.4"
pin-project = "1.1.5"
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
    "stream",
    "rustls",
    "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
structopt = "0.3"
tokio = { version = "1.36", features = ["macros"] }
tokio-stream = { version = "0.1.14", features = ["fs"] }
tokio-tar = "0.3.1"
tokio-util = "0.7.10"

[dev-dependencies]
tokio = { version = "1.35", features = ["macros", "rt"] }
