name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    name: "publish"

    # Reference your environment variables
    environment: cargo

    steps:
      - uses: actions/checkout@master

      # Use caching to speed up your build
      - name: Cache publish-action bin
        id: cache-publish-action
        uses: actions/cache@v3
        env:
          cache-name: cache-publish-action
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - uses: actions-rs/toolchain@v1
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        with:
          toolchain: stable

      - name: Install cargo-deb
        if: steps.cache-publish-action.outputs.cache-hit != 'true'
        run: cargo install cargo-deb

      - name: Run cargo publish libprotonup
        run: cargo publish -p libprotonup
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Run cargo build
        run: cargo build --release

      - name: Run cargo-deb to build a debian package
        run: cargo-deb -p protonup-rs --deb-version ${{ github.ref }}

      - name: Run cargo publish binary
        run: cargo publish -p protonup-rs
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Upload Tar gzed binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/protonup-rs-linux-amd64.tar.gz
          asset_name: protonup-rs-linux-amd64.tar.gz
          tag: ${{ github.ref }}

      - name: Upload Ziped binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/protonup-rs-linux-amd64.zip
          asset_name: protonup-rs-linux-amd64.zip
          tag: ${{ github.ref }}

      - name: Upload deb package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /app/target/debian/protonup-rs_${{ github.ref }}-1_amd64.deb
          asset_name: /app/target/debian/protonup-rs_${{ github.ref }}-1_amd64.deb
          tag: ${{ github.ref_name }}

