name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Update local toolchain
        run: |
          rustup update
          rustup install stable

      - name: Test
        run: |
          cargo check
          cargo test --all

      - name: Build
        run: |
          cargo build --release
